"""Exporter: CSV, XLSX, JSON, Parquet with optional provenance columns."""
from __future__ import annotations

import io
import json
from datetime import datetime, timezone
from typing import Any



def _clean_records(
    records: list[dict],
    include_provenance: bool = True,
) -> list[dict]:
    """Strip internal _ fields unless provenance requested."""
    result = []
    for rec in records:
        row: dict[str, Any] = {}
        prov: dict[str, Any] = {}
        for k, v in rec.items():
            if k.startswith('_'):
                if include_provenance:
                    prov[k.lstrip('_')] = v
            else:
                row[k] = v
        if include_provenance:
            row.update({f"prov:{k}": v for k, v in prov.items()})
        result.append(row)
    return result


def export_json(records: list[dict], include_provenance: bool = True) -> bytes:
    clean = _clean_records(records, include_provenance)
    return json.dumps(clean, indent=2, default=str).encode()


def export_csv(records: list[dict], include_provenance: bool = True) -> bytes:
    import pandas as pd
    clean = _clean_records(records, include_provenance)
    if not clean:
        return b""
    df = pd.DataFrame(clean)
    buf = io.BytesIO()
    df.to_csv(buf, index=False)
    return buf.getvalue()


def export_xlsx(records: list[dict], include_provenance: bool = True) -> bytes:
    import pandas as pd
    clean_data = _clean_records(records, include_provenance=False)

    if not clean_data:
        return b""

    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine='openpyxl') as writer:
        # Sheet 1: Data
        pd.DataFrame(clean_data).to_excel(writer, sheet_name='Data', index=False)
        # Sheet 2: Sources (provenance)
        prov_rows = []
        for rec in records:
            prov_rows.append({
                'source_url': rec.get('_source_url', ''),
                'extraction_method': rec.get('_extraction_method', ''),
                'quality_score': rec.get('_quality_score', ''),
            })
        pd.DataFrame(prov_rows).to_excel(writer, sheet_name='Sources', index=False)
        # Sheet 3: README
        readme_df = pd.DataFrame([{
            'field': 'Generated by', 'value': 'ScoutIQ'
        }, {
            'field': 'Generated at', 'value': datetime.now(timezone.utc).isoformat()
        }, {
            'field': 'Record count', 'value': len(records)
        }, {
            'field': 'No-fabrication guarantee',
            'value': 'Every cell traces to a source URL and verified evidence snippet'
        }])
        readme_df.to_excel(writer, sheet_name='README', index=False)
    return buf.getvalue()


def export_parquet(records: list[dict], include_provenance: bool = True) -> bytes:
    import pandas as pd
    import pyarrow as pa
    import pyarrow.parquet as pq

    clean = _clean_records(records, include_provenance)
    if not clean:
        return b""
    df = pd.DataFrame(clean)
    # Convert all columns to string to avoid type issues
    for col in df.columns:
        df[col] = df[col].astype(str)
    table = pa.Table.from_pandas(df)
    buf = io.BytesIO()
    pq.write_table(table, buf)
    return buf.getvalue()
